# Generated by Django 4.1 on 2022-11-03 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_participantaddress_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='pass', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
