# Generated by Django 4.1 on 2022-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_addevent_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addevent',
            options={'verbose_name_plural': '3. Add Event'},
        ),
        migrations.AlterModelOptions(
            name='eventcategotry',
            options={'verbose_name_plural': '2. Event Category'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': '1. Hosts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '5. Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': '6. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='participantaddress',
            options={'verbose_name_plural': '7. Participant Address'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name_plural': '4. Participants'},
        ),
        migrations.AddField(
            model_name='host',
            name='last_name',
            field=models.CharField(default='name', max_length=100, null=True),
        ),
    ]
