# Generated by Django 4.1 on 2022-11-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_participants_name_alter_host_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='main.eventcategotry'),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.host'),
        ),
    ]
