# Generated by Django 4.1 on 2022-11-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_addevent_category_alter_addevent_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addevent',
            options={'verbose_name_plural': '3. Add Events'},
        ),
        migrations.RenameField(
            model_name='addevent',
            old_name='title',
            new_name='event_name',
        ),
    ]
