# Generated by Django 4.1.4 on 2023-01-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
