# Generated by Django 4.1.4 on 2023-02-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('token_blacklist', '0011_linearizes_history'),
        ('account', '0002_email_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('social_django', '0011_alter_association_id_alter_code_id_alter_nonce_id_and_more'),
        ('authtoken', '0003_tokenproxy'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('main', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='Users',
        ),
    ]
